name: bump

on:
  schedule:
    - cron: "0 22 * * 1-5" # every weekday at 22:00 UTC
  workflow_dispatch:
    inputs:
      force:
        description: "force"
        required: false
        type: choice
        default: "true"
        options:
          - "true"
          - "false"

# yaml-language-server-disable is not allowed
enable-openid-connect: true

jobs:
  bump:
    # zizmor: ignore[excessive-permissions]
    runs-on: ubuntu-24.04
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@2fc360eefced0d01fc56eaf691ab9393a94a1c60 # v1.60.0
        with:
          token: ${{ secrets.DOCTOR_TOKEN }}
          github_token: ${{ secrets.GH_TOKEN }}
          niks3_url: https://niks3.trev.zip
          fetch_depth: 0
          shell: bump

      - name: Bump
        run: bumper
        env:
          GITHUB_TOKEN: ${{ secrets.DOCTOR_TOKEN }}
          FORCE: ${{ inputs.force }}
