name: check

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}

# yaml-language-server-disable is not allowed
enable-openid-connect: true

jobs:
  check:
    # zizmor: ignore[excessive-permissions]
    runs-on: ubuntu-24.04
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@52b7e46ef1fb211e25e0f91e0ba9fdf2cb1c34e2 # v1.64.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          niks3_url: https://niks3.trev.zip

      - name: Check
        run: nix flake check
