name: check

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}

# yaml-language-server-disable is not allowed
enable-openid-connect: true

jobs:
  check:
    # zizmor: ignore[excessive-permissions]
    runs-on: ubuntu-24.04
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@c2709c977467ea3c9a12f82fe48922ce49947a2d # v1.53.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          niks3_url: https://niks3.trev.zip

      - name: Check
        run: nix flake check
