name: label

on:
  pull_request_target:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}

jobs:
  label:
    # zizmor: ignore[excessive-permissions]
    runs-on: ubuntu-26.04
    steps:
      - name: Label
        uses: actions/labeler@bf12e9b00b37c5c0ca2b87b79b2daf7891dbda13 # v7.0.0
        with:
          configuration-path: .forgejo/labeler.yaml
