name: release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

# yaml-language-server-disable is not allowed
enable-openid-connect: true

jobs:
  linux:
    # zizmor: ignore[excessive-permissions]
    runs-on: ubuntu-24.04
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@d4c575df910b35487710048791c2ae11eefbac3e # v1.48.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          niks3_url: https://niks3.trev.zip
          token: ${{ secrets.DOCTOR_TOKEN }}
          fetch_depth: 0
          shell: release

      - name: Release to Forgejo
        run: flake-release
        env:
          GITHUB_TOKEN: ${{ secrets.DOCTOR_TOKEN }}
          REGISTRY: trev.zip
          REGISTRY_PASSWORD: ${{ secrets.PACKAGE_TOKEN }}
          DELETE_OLD_RELEASE_ARTIFACTS: true
          PACKAGES: |
            packages.x86_64-linux.default.x86_64-unknown-linux-musl
            packages.x86_64-linux.default.aarch64-unknown-linux-musl
            packages.x86_64-linux.default.armv7l-unknown-linux-musleabihf
            packages.x86_64-linux.default.x86_64-w64-mingw32
            images.x86_64-linux.default.x86_64-unknown-linux-musl
            images.x86_64-linux.default.aarch64-unknown-linux-musl
            images.x86_64-linux.default.armv7l-unknown-linux-musleabihf
