name: update

on:
  schedule:
    - cron: "0 9 * * *" # every day at 09:00 UTC
  workflow_dispatch:
    inputs:
      debug:
        description: Enable Renovate debug logging
        required: false
        type: boolean
        default: false

# yaml-language-server-disable is not allowed
enable-openid-connect: true

jobs:
  renovate:
    # zizmor: ignore[excessive-permissions]
    runs-on: ubuntu-24.04
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@48b6d3dd393260451050b0e6b78bc51fc483d500 # v1.58.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          niks3_url: https://niks3.trev.zip
          shell: update

      - name: Renovate
        run: renovate
        env:
          RENOVATE_CONFIG_FILE: .forgejo/renovate.json
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_GITHUB_COM_TOKEN: ${{ secrets.GH_TOKEN }}
          LOG_LEVEL: ${{ inputs.debug && 'debug' || 'info' }}
