name: bump

on:
  schedule:
    - cron: "0 22 * * 1-5" # every weekday at 22:00 UTC
  workflow_dispatch:
    inputs:
      force:
        description: "force"
        required: false
        type: choice
        default: "true"
        options:
          - "true"
          - "false"

concurrency:
  group: release

permissions:
  contents: read

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - id: init
        name: Initialize
        uses: spotdemo4/nix-init@78cb37091fca621cf273ed076027ebfbaf906457 # v1.44.2
        with:
          app_id: ${{ vars.CLIENT_ID }}
          app_key: ${{ secrets.PRIVATE_KEY }}
          fetch_depth: 0
          shell: bump

      - name: Bump
        run: bumper
        env:
          GITHUB_TOKEN: ${{ steps.init.outputs.token }}
          FORCE: ${{ inputs.force }}
          PATHS: README.md
