name: bump

on:
  schedule:
    - cron: "0 22 * * 1-5" # every weekday at 22:00 UTC
  workflow_dispatch:
    inputs:
      force:
        description: "force"
        required: false
        type: choice
        default: "true"
        options:
          - "true"
          - "false"

concurrency:
  group: release

permissions:
  contents: read
  id-token: write

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - id: init
        name: Initialize
        uses: spotdemo4/nix-init@0570d65d7c69d827384b0749108a291c40b67b34 # v1.44.1
        with:
          app_id: ${{ vars.CLIENT_ID }}
          app_key: ${{ secrets.PRIVATE_KEY }}
          fetch_depth: 0
          shell: bump

      - name: Bump
        run: bumper
        env:
          GITHUB_TOKEN: ${{ steps.init.outputs.token }}
          FORCE: ${{ inputs.force }}
          PATHS: |
            action.yaml
            .github/README.md
