name: check

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}

permissions:
  contents: read

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-26.04
          - ubuntu-26.04-arm
          - macos-26
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    permissions:
      id-token: write
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@90fe0da793883e878fa0a09ac2979190074920c4 # v1.67.0

      - name: Check
        run: nix flake check
