name: release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

concurrency:
  group: release

permissions:
  contents: read

jobs:
  linux-amd64:
    name: linux amd64
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: write
      packages: write
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@d4c575df910b35487710048791c2ae11eefbac3e # v1.48.0
        with:
          fetch_depth: 0
          shell: release

      - name: Release to GitHub
        run: flake-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGES: |
            packages.x86_64-linux.default
            images.x86_64-linux.default

  linux-arm64:
    name: linux arm64
    runs-on: ubuntu-24.04-arm
    permissions:
      id-token: write
      contents: write
      packages: write
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@d4c575df910b35487710048791c2ae11eefbac3e # v1.48.0
        with:
          fetch_depth: 0
          shell: release

      - name: Release to GitHub
        run: flake-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGES: |
            packages.aarch64-linux.default
            images.aarch64-linux.default

  darwin-arm64:
    name: darwin arm64
    runs-on: macos-26
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@d4c575df910b35487710048791c2ae11eefbac3e # v1.48.0
        with:
          fetch_depth: 0
          shell: release

      - name: Release to GitHub
        run: flake-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGES: |
            packages.aarch64-darwin.default
