name: update

on:
  # schedule:
  #   - cron: "0 9 * * *" # every day at 09:00 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-26.04
    permissions:
      id-token: write
    steps:
      - id: init
        name: Initialize
        uses: spotdemo4/nix-init@90fe0da793883e878fa0a09ac2979190074920c4 # v1.67.0
        with:
          app_id: ${{ vars.CLIENT_ID }}
          app_key: ${{ secrets.PRIVATE_KEY }}
          shell: update

      - name: Renovate
        run: renovate
        env:
          RENOVATE_CONFIG_FILE: .github/renovate.json
          RENOVATE_TOKEN: ${{ steps.init.outputs.token }}
          LOG_LEVEL: ${{ runner.debug == '1' && 'debug' || 'info' }}
