name: vulnerable

on:
  schedule:
    - cron: "0 9 * * 0" # every Sunday at 09:00 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  actions:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@3215144ef6367f915ece1867ff66e63ad92bd9f4 # v1.62.1
        with:
          shell: vulnerable

      - name: Run zizmor
        run: zizmor $(find .github/workflows -name "*.yaml")

  nix:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@3215144ef6367f915ece1867ff66e63ad92bd9f4 # v1.62.1
        with:
          shell: vulnerable

      - name: Run flake-checker
        run: flake-checker -f
