name: vulnerable

on:
  schedule:
    - cron: "0 9 * * 0" # every Sunday at 09:00 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  actions:
    runs-on: ubuntu-26.04
    permissions:
      id-token: write
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@90fe0da793883e878fa0a09ac2979190074920c4 # v1.67.0
        with:
          shell: vulnerable

      - name: Run zizmor
        run: zizmor $(find .github/workflows -name "*.yaml")

  nix:
    runs-on: ubuntu-26.04
    permissions:
      id-token: write
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@90fe0da793883e878fa0a09ac2979190074920c4 # v1.67.0
        with:
          shell: vulnerable

      - name: Run flake-checker
        run: flake-checker -f
